services:
  sbg-shutupgallery-landing-ddbb:
    container_name: sbg-shutupgallery-landing-ddbb
    # We use a mariadb image which supports both amd64 & arm64 architecture
    # image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12f!8fwq5p#e6
      - MYSQL_DATABASE=sgwpdb
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=dwu3F2nfldwjjd2n.
    expose:
      - 33062:3306

  sbg-shutupgallery-wp:
    container_name: sbg-shutupgallery-wp
    image: wordpress:latest
    ports:
      - 11000:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=sbg-shutupgallery-landing-ddbb
      - WORDPRESS_DB_NAME=sgwpdb
      - WORDPRESS_DB_USER=developer
      - WORDPRESS_DB_PASSWORD=dwu3F2nfldwjjd2n.
      
    # volumes:
    #   - wp_data:/var/www/html
    #   - ${PWD}/src/configs/.htaccess:/var/www/html/.htaccess
    #   - ${PWD}/src/configs/php.ini:/usr/local/etc/php/conf.d/php.ini
    #   - ${PWD}/src/x.io-20240209-105457-dk2hht.wpress:/var/www/html/wp-content/ai1wm-backups/x.io-20240209-105457-dk2hht.wpress

volumes:
  db_data:
  # wp_data:

  haproxy:
    image: valian/docker-nginx-auto-ssl:1.0.0
    container_name: haproxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.vol-ssl-data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'compositly.com'
      SITES: "_=sbg-shutupgallery-wp:80;*.compositly.com=sbg-shutupgallery-wp:80;int-shutupgallery.compositly.com=sbg-shutupgallery-wp:80"
      FORCE_HTTPS: "true"
      RESOLVER_ADDRESS: "8.8.8.8"
      LETSENCRYPT_URL: 'https://acme-v02.api.letsencrypt.org/directory'
